eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: cache-client
  redis:
    database: 0        # Redis数据库索引（默认为0）
    host: localhost    # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100    # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20       # 连接池中的最大空闲连接
    min-idle: 0        # 连接池中的最小空闲连接
    timeout: 3000      # 连接超时时间（毫秒）